title: Igor Fesenko, Ph.D. # Add a space after the period

#logo: "Me.png" # Use a relative path to logo image
logo: Me.png

description: Peptides and small proteins # Fix hyphenation 
baseurl: ""
url: "https://IgorFesenko.github.io"


author:
  name: "Igor Fesenko"
  email: "fesigor@gmail.com"

theme: jekyll-theme-minimal 
#theme: jekyll-al-folio

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

social_links:
  twitter: https://twitter.com/FesenkoIgor
  github: https://github.com/IgorFesenko
  linkedin: https://www.linkedin.com/in/igor-fesenko-0a83691a8

