title: Igor Fesenko, Ph.D. # Add a space after the period

#logo: Me.png # Use a relative path to logo image 

description: Computational Biologist # Fix hyphenation 
baseurl: ""
url: "https://IgorFesenko.github.io"
#show_downloads: false # Fix spelling
author:
  name: "Igor Fesenko"
  email: "fesigor@gmail.com"

theme: jekyll-theme-cayman 

plugins:
  - jekyll-seo-tag # Add SEO plugin

social_links:
  twitter: https://twitter.com/FesenkoIgor
  github: https://github.com/IgorFesenko
  linkedin: https://www.linkedin.com/in/igor-fesenko-0a83691a8

